[project]
name = "web-greeter"
version = "4.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dataclass-binder>=0.3.5",
    "inotify>=0.2.12",
    "pygobject>=3.54.5",
    "pyside6>=6.10.0",
]

# [build-system]
# requires = ["uv_build >= 0.9.5, <0.10.0"]
# build-backend = "uv_build"

[tool.pyside6-project]
files = ["./src/__main__.py", "./src/resources/resources.qrc"]

[tool.ruff]
line-length = 88

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[dependency-groups]
dev = [
    "nuitka>=4.0.1",
    "ordered-set>=4.1.0",
    "patchelf>=0.17.2.4",
    "zstandard>=0.25.0",
]
