.TH "web-greeter" "1" "2022.2.10"
.nh
.ad l
.SH "NAME"
web-greeter
.SH "SYNOPSIS"
.PP
LightDM greeter that uses chromium for theming via HTML/JavaScript\&.
.PP
.SH "DESCRIPTION"
.PP
web-greeter is a LightDM greeter that uses chromium for theming\&.  Themes can be written
using a combination of HTML and Javascript\&.
.PP
.SH "OPTIONS"
.TP
\fB\-h, \-\-help\fR
Shows the help
.TP
\fB\-v, \-\-version\fR
Print program version
.TP
\fB\-\-debug\fR
Forces the greeter to run in debug mode
.TP
\fB\-\-normal\fR
Forces the greeter to run in normal mode
.TP
\fB\-\-list\fR
Shows the available themes
.TP
\fB\-\-theme\ \fITHEME\fR
Sets the theme to use
.PP
.SH "THEME JAVASCRIPT API"
Please note that all properties and functions which are marked as "deprecated" are
only available for backwards compatibility and will be removed in a future version of
web-greeter\&.  Theme authors should not use any deprecated properties or
functions in new works and should update any existing works which make use of
deprecated properties and/or functions to ensure continued proper functionality\&.
.PP
See full documentation on https://jezerm\&.github\&.io/web-greeter/
.PP
The following signals are available to connect javascript functions when a LightDM
or web-greeter signal occurs:
.PP
\fBlightdm.authentication_complete\fR
.RS 4
Gets emitted when the greeter has completed authentication\&.
.RE
.PP
\fBlightdm.autologin_timer_expired\fR
.RS 4
Gets emitted when the automatic login timer has expired\&.
.RE
.PP
\fBlightdm.show_message\fR
.RS 4
Gets emitted when the greeter should show a message to the user\&.
This signal emits a \fBmessage: string\fR and a \fBtype: number\fR\&.
.RE
.PP
\fBlightdm.show_prompt\fR
.RS 4
Gets emitted when the greeter should show a prompt to the user\&.
This signal emits a \fBmessage: string\fR and a \fBtype: number\fR\&.
.RE
.PP
The following functions are available for the greeter to call to execute
actions within LightDM:
.PP
\fBlightdm\&.authenticate(username)\fR
.RS 4
Specifies the username of the user we'd like to start authenticating as\&.  Note that
if you call lightdm.authenticate with no argument, LightDM (via PAM) will issue
a show_prompt() call to ask for the username\&.
.RE
.PP
\fBlightdm\&.authenticate_as_guest()\fR
.RS 4
Authenticates as the guest user\&.
.RE
.PP
\fBlightdm\&.cancel_authentication()\fR
.RS 4
Cancels the authentication of any user currently in the process of
authenticating\&.
.RE
.PP
\fBlightdm\&.cancel_autologin()\fR
.RS 4
Cancels the authentication of the autologin user\&.
.RE
.PP
\fBlightdm\&.start_session(session)\fR
.RS 4
Once LightDM has successfully authenticated the user, start the user's session
by calling this function\&.  "session" is the authenticated user's session\&.
If no session is passed, start the authenticated user with the system default
session.
.RE
.PP
\fBlightdm\&.respond(text)\fR
.RS 4
When LightDM has prompted for input, provide the response to LightDM\&.
.RE
.PP
\fBlightdm\&.set_language(lang)\fR
.RS 4
Will set the language for the current LightDM session\&.
.RE
.PP
\fBlightdm\&.shutdown()\fR
.RS 4
Shuts down the system, if the greeter has the authority to do so\&.
Check if greeter can shutdown with \fBlightdm\&.can_shutdown\fR
.RE
.PP
\fBlightdm\&.restart()\fR
.RS 4
Restarts the system, if the greeter has the authority to do so\&.
Check if greeter can restart with \fBlightdm\&.can_restart\fR
.RE
.PP
\fBlightdm\&.suspend()\fR
.RS 4
Suspends the system, if the greeter has the authority to do so\&.
Check if greeter can suspend with \fBlightdm\&.can_suspend\fR
.RE
.PP
\fBlightdm\&.hibernate()\fR
.RS 4
Hibernates the system, if the greeter has the authority to do so\&.
Check if greeter can hibernate with \fBlightdm\&.can_hibernate\fR
.RE
.PP
Variables available within the greeter are:
.PP
\fBlightdm\&.authentication_user\fR: string
.RS 4
The username of the authentication user being authenticated or null if no
authentication is in progress\&.
.RE
.PP
\fBlightdm\&.autologin_guest\fR: boolean
.RS 4
Indicates the guest user should be used for autologin\&.
.RE
.PP
\fBlightdm\&.autologin_timeout\fR: number
.RS 4
The number of seconds to wait before automatically logging in\&.
.RE
.PP
\fBlightdm\&.autologin_user\fR: string
.RS 4
The name of the user account that should be logged into
automatically after timed login delay has passed\&.
.RE
.PP
\fBlightdm\&.can_hibernate\fR: boolean
.RS 4
Whether or not the system can be made to hibernate by the greeter\&.
.RE
.PP
\fBlightdm\&.can_restart\fR: boolean
.RS 4
Whether or not the system can be restarted by the greeter\&.
.RE
.PP
\fBlightdm\&.can_shutdown\fR: boolean
.RS 4
Whether or not the system can be shutdown by the greeter\&.
.RE
.PP
\fBlightdm\&.can_suspend\fR: boolean
.RS 4
Whether or not the system can be suspended by the greeter\&.
.RE
.PP
\fBlightdm\&.default_session\fR: string
.RS 4
The name of the default session (as configured in lightdm.conf)\&.
.RE
.PP
\fBlightdm\&.has_guest_account\fR: boolean
.RS 4
A guest account is available for login\&.
.RE
.PP
\fBlightdm\&.hide_users_hint\fR: boolean
.RS 4
The whole list of users should not be displayed\&.
.RE
.PP
\fBlightdm\&.hostname\fR: string
.RS 4
The hostname of the system\&.
.RE
.PP
\fBlightdm\&.is_authenticated\fR: boolean
.RS 4
Indicates if the user has successfully authenticated\&.
.RE
.PP
\fBlightdm\&.in_authentication\fR: boolean
.RS 4
Indicates if lightdm is currently in the authentication phase\&.
.RE
.PP
\fBlightdm\&.language\fR: LightDM.Language | null
.RS 4
The currently selected language\&.
.RE
.PP
\fBlightdm\&.languages\fR: LightDM.Languages[]
.RS 4
The languages that are available on the system\&.
.RE
.PP
\fBlightdm\&.layout\fR: LightDM.Layout
.RS 4
The currently active layout for the selected user.
.RE
.PP
\fBlightdm\&.layouts\fR: LightDM.Layout[]
.RS 4
The keyboard layouts that are available on the system\&.
.RE
.PP
\fBlightdm\&.select_guest_hint\fR: boolean
.RS 4
The guest user should be selected by default for login\&.
.RE
.PP
\fBlightdm\&.select_user_hint\fR: string
.RS 4
The username that should be selected by default for login\&.
.RE
.PP
\fBlightdm\&.sessions\fR: LightDM.Session[]
.RS 4
The sessions that are available on the system\&.
.RE
.PP
\fBlightdm\&.users\fR: LightDM.User[]
.RS 4
The users that are able to log in\&. Returns an Array of LightDMUser
objects\&.
.RE
.PP
The \fBtheme_utils\fR object has some utility functions associated with it which
are intended to make a theme author's work easier\&.
.PP
\fBtheme_utils\&.dirlist(path)\fR
.RS 4
Returns an array of strings of filenames present at "path", or Null if the
path does not exist\&.
.RE
.PP
\fBtheme_utils\&.bind_this(context)\fR
.RS 4
Binds this to class, context, for all of the class's methods\&.
.RE
.PP
\fBtheme_utils\&.get_current_localized_time()\fR
.RS 4
Get the current time in a localized format\&. Language is auto-detected by default,
but can be set manually in the greeter config file\&.
.RE
\fBtheme_utils\&.get_current_localized_date()\fR
.RS 4
Get the current date in a localized format\&. Language is auto-detected by default,
but can be set manually in the greeter config file\&.
.RE
.PP
Please see the LightDM API documentation for the complete list of calls
available\&. The web-greeter implements all of the LightDM API\&.
.PP
.SH "CONFIGURATION"
.PP
\fB/etc/lightdm/web-greeter\&.yml\fR
.RS 4
Configuration file\&.
.RE
.SH "FILES"
.PP
\fB/usr/share/web-greeter/themes\fR
.RS 4
Directory where themes should be stored\&.
.RE
.SH "EXAMPLES"
.PP
Please see the "dracula", "gruvbox" and "simple" themes that are shipped with web-greeter\&.
.TP
\fBCommand Line\fR
.RS 4
web-greeter --theme simple --debug
.TP
web-greeter --normal
.SH "SEE ALSO"
.PP
http://people\&.ubuntu\&.com/~robert-ancell/lightdm/reference/
.PP
https://lazka\&.github\&.io/pgi-docs/#LightDM-1
.PP
https://jezerm\&.github\&.io/web-greeter/
.PP
https://github.com/JezerM/web-greeter
.SH "AUTHOR"
.PP
The legacy lightdm-webkit-greeter was written by Robert Ancell <robert\&.ancell\&@canonical\&.com\&>\&.
It was ported to webkit2 by the Antergos Developers <dev@antergos\&.com>\&. Also includes code improvements
contributed by Scott Balneaves <sbalneav@ltsp\&.org>\&. Forked and mantained by JezerM <amyuki4@gmail\&.com>\&.
