name: Build Test

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout local actions
      uses: actions/checkout@v2
    -
      name: Build and install web-greeter
      uses: "./.github/actions/build"
      with:
        target-distro: ubuntu
  build-debian:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout local actions
      uses: actions/checkout@v2
    -
      name: Build web-greeter
      uses: "./.github/actions/build"
      with:
       target-distro: debian