name: Build Test

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/build.yml"
      - ".github/actions/build/action.yml"
  pull_request:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout local actions
      uses: actions/checkout@v2
      with:
        submodules: recursive
    -
      name: Build and install web-greeter
      uses: "./.github/actions/build"
      with:
        target-distro: ubuntu
  build-debian:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout local actions
      uses: actions/checkout@v2
      with:
        submodules: recursive
    -
      name: Build web-greeter
      uses: "./.github/actions/build"
      with:
       target-distro: debian
